# 1111
# Layout toggle
source = ~/.config/hypr/conf/keyboard.conf

# Monitors 
source = ~/.config/hypr/conf/monitors.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Variables
source = ~/.config/hypr/conf/variables.conf

# ENV
source = ~/.config/hypr/conf/env.conf

# Keybind
source = ~/.config/hypr/conf/keybind.conf

# General
source = ~/.config/hypr/conf/general.conf

# Decoration
source = ~/.config/hypr/conf/decoration.conf

# Animation
source = ~/.config/hypr/conf/animation.conf


# Workspacws
source = ~/.config/hypr/conf/workspace.conf

# Windowrules
source = ~/.config/hypr/windowrule/nautilus.conf
source = ~/.config/hypr/windowrule/waypaper.conf
source = ~/.config/hypr/windowrule/loupe.conf


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}


# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}



##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
