# Отправляем в специальный карман
windowrule = match:class ^(brave-browser)$, workspace special:brave

# Вызов/скрытие кармана с Telegram
bind = $mainMod, S, togglespecialworkspace, brave 

# Autostart
exec-once = [workspace special:brave silent] brave-browser 
