# Отправляем в специальный карман
windowrule = match:class ^(org.telegram.desktop)$, workspace special:telegram

# Вызов/скрытие кармана с Telegram
bind = $mainMod, T, togglespecialworkspace, telegram

# Autostart
exec-once = [workspace special:telegram silent] org.telegram.desktop
