#################
### AUTOSTART ###
#################

# Walpeppers
exec-once = awww-daemon
exec-once = waypaper --restore

exec-once = waybar

# Auto keyboard switcher
exec-once = hyprland-per-window-layout
